#!/usr/bin/env node
// build.js — generates the static pages for chess.kimuli.me from openings.js
//
//   node build.js
//
// Generates (all committed, and regenerated by CI before every deploy):
//   white/index.html, black/index.html            — per-side opening lists
//   <side>/<opening>/<variation>/index.html       — the lesson viewer route
//   sitemap.xml, robots.txt
//
// To add an opening: edit openings.js (add an entry with side / opening /
// variation / route), then run this script. Nothing else to touch.

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = __dirname;
const SITE = "https://chess.kimuli.me";

// ── load the registry straight out of openings.js ────────────────────────────
function loadOpenings() {
  const src = fs.readFileSync(path.join(ROOT, "openings.js"), "utf8");
  const ctx = { console };
  vm.createContext(ctx);
  vm.runInContext(src + "\n;this.__OPENINGS__ = OPENINGS;", ctx);
  return ctx.__OPENINGS__;
}

const SIDES = {
  white: {
    title: "Openings for White",
    sub: "Build a repertoire with the first move — space, initiative, and a plan you understand.",
    badge: "♙ White"
  },
  black: {
    title: "Openings for Black",
    sub: "Fighting defences that unbalance the game and play for a win, not a draw.",
    badge: "♟ Black"
  }
};

const esc = s => String(s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;");

const variationName = o => o.subtitle.split(" — ")[0];

function write(relPath, content) {
  const full = path.join(ROOT, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
  return relPath;
}

// ── per-side list page ───────────────────────────────────────────────────────
function sidePage(sideSlug, entries) {
  const side = SIDES[sideSlug];
  const cards = entries.map(o => `
      <a class="opening-card" href="/${o.route}/">
        <span class="side-badge badge-${o.side}">${esc(o.name)}</span>
        <h2 class="card-title">${esc(variationName(o))}</h2>
        <p class="card-subtitle">${o.moves.length} steps &middot; main line</p>
        <p class="card-line">${esc(o.line)}</p>
        <p class="card-blurb">${esc(o.blurb)}</p>
        <span class="card-cta">Start lesson &#8594;</span>
      </a>`).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(side.title)} — Chess Openings | chess.kimuli.me</title>
  <meta name="description" content="${esc(side.sub)}">
  <link rel="stylesheet" href="/style.css">
</head>
<body>
  <div class="app landing">
    <header class="landing-hero">
      <a class="back-link" href="/">&#8592; All openings</a>
      <h1 class="hero-title">${esc(side.title)}</h1>
      <p class="hero-sub">${esc(side.sub)}</p>
    </header>

    <main class="openings-grid">
${cards}
    </main>

    <footer class="app-footer">
      <a href="https://kimuli.me">kimuli.me</a>
    </footer>
  </div>
</body>
</html>
`;
}

// ── lesson route page (viewer shell with the opening baked in) ────────────────
function routePage(shell, o) {
  const title = `${o.name} — ${o.subtitle} | chess.kimuli.me`;
  const desc = `${o.name} (${o.subtitle}) — a step-by-step chess opening guide, move by move.`;

  return shell
    .replace(/<title id="page-title">[^<]*<\/title>/,
      `<title id="page-title">${esc(title)}</title>`)
    .replace(/<meta id="page-description" name="description" content="[^"]*">/,
      `<meta id="page-description" name="description" content="${esc(desc)}">`)
    .replace('<script src="/openings.js"></script>',
      `<script>window.OPENING_KEY = ${JSON.stringify(o.key)};</script>\n  <script src="/openings.js"></script>`);
}

// ── run ──────────────────────────────────────────────────────────────────────
const OPENINGS = loadOpenings();
const all = Object.values(OPENINGS);
const shell = fs.readFileSync(path.join(ROOT, "viewer.html"), "utf8");
const written = [];

for (const sideSlug of Object.keys(SIDES)) {
  const entries = all.filter(o => o.side === sideSlug)
    .sort((a, b) => a.name.localeCompare(b.name) || a.variation.localeCompare(b.variation));
  if (!entries.length) continue;
  written.push(write(`${sideSlug}/index.html`, sidePage(sideSlug, entries)));
}

for (const o of all) {
  if (!o.route) throw new Error(`opening "${o.key}" has no route`);
  const expected = `${o.side}/${o.opening}/${o.variation}`;
  if (o.route !== expected) throw new Error(`opening "${o.key}" route "${o.route}" != "${expected}"`);
  written.push(write(`${o.route}/index.html`, routePage(shell, o)));
}

// sitemap + robots
const urls = [`${SITE}/`]
  .concat(Object.keys(SIDES).filter(s => all.some(o => o.side === s)).map(s => `${SITE}/${s}/`))
  .concat(all.map(o => `${SITE}/${o.route}/`));

written.push(write("sitemap.xml",
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  urls.map(u => `  <url><loc>${u}</loc></url>`).join("\n") + `\n</urlset>\n`));

written.push(write("robots.txt", `User-agent: *\nAllow: /\nSitemap: ${SITE}/sitemap.xml\n`));

console.log(`build.js — ${all.length} opening(s), ${written.length} file(s) written:`);
written.forEach(f => console.log("  " + f));
